### ISSUE TITLE
Musl incompatible

### ISSUE THREAD

**Issue by not-kaz** [valters-tomsons/DayZLauncher-UnixPatcher#2]
Hey Valters,

Great job on this, I really like that I don't have to run any third-party TUI/CLI/GUI.

It worked great on my glibc based distro, however, on my main device running musl it doesn't run.
It just says 'No such file or directory.' (Even without the file path arguement, I get no prompt to type it and press enter, like on the other distro.) 

Running it as a script, making it executable again via chmod +x, makes no difference.

Do you have any idea how to fix it or is it unfortunately something we will have to accept will not run?

Keep up the great work!

**Comment by valters-tomsons** [comment]
Hey, thanks for the feedback!

Sadly, I have never used a desktop musl-based distribution, in fact, I didn't know you can run steam and wine games there.

That being said, below you will find `1.2.7` built targeting musl-c. It's not tested at all, so please report back :)

[DayZLauncher-UnixPatcher_1.2.7-MUSL.zip](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/files/11469711/DayZLauncher-UnixPatcher_1.2.7-MUSL.zip)
