### ISSUE TITLE
Configuration is broken on latest release

### ISSUE THREAD

**Issue by raku-cat** [valters-tomsons/DayZLauncher-UnixPatcher#4]
Trying this with the latest version, does allow mods to start downloading but they get stuck in "not installed" like below:
![image](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/assets/1125449/07ba2685-e923-4b3e-abf0-c7025d7c90d2)
Hovering the icon shows a message saying "the path for the mod folder is not set".
Also, the launcher settings patch doesn't seem to be working either.

**Comment by valters-tomsons** [comment]
Will take a look :eyes:

**Comment by okseb** [comment]
Any progress?

**Comment by valters-tomsons** [comment]
Please test this:
https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/releases/tag/1.2.8-dev0

Configuration is seriously broken, not sure how to approach it or what's even going wrong. Can't promise anything, since I haven't been playing the game recently.

**Comment by okseb** [comment]
This works and the mod functionality is all I really care about. So if the configuration is too much work to figure out, for me its not a big deal.

**Comment by valters-tomsons** [comment]
Fixed as of https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/commit/7fb27931b2f0b1456954b1553d54cf898856d219
