### ISSUE TITLE
Im new and need help 

### ISSUE THREAD

**Issue by nhill308** [valters-tomsons/DayZLauncher-UnixPatcher#5]
Im new to all this stuff , like fresh off the truck kinda new . I have no idea what to do with this or how to implement it . In the directions stem 2 says Launch DayZLauncher.UnixPatcher with full DayZ installation path as argument
(eg. ./DayZLauncher.UnixPatcher "/primary/SteamLibrary/steamapps/common/DayZ/") ... how do i launch it ? like what steps do i take what do i use . Sorry im just so new to all this i fell a little dumb lol

**Comment by valters-tomsons** [comment]
1. Select DayZ in Steam and right-click it
2. Hover Properties, then click Browse Local Files
3. A file browser should open with game's install directory
4. Copy the path of this directory (for example: `/home/deck/.steam/steam/steamapps/common/DayZ/`)
5. Download the UnixPatcher and extract the downloaded archive, it will contain a folder, open it
6. Make `DayZLauncher.UnixPatcher` file executable by running `chmod +x ./DayZLauncher.UnixPatcher` from terminal inside this folder, or by using your file manager's options (something like: right click the file, click properties, check "allow running as executable" )
7. Launch DayZLauncher.UnixPatcher, it will ask for DayZ installation directory
8. Copy or type exactly the path you had in step 4

**Comment by nhill308** [comment]
Thanks for the help . This makes it much easier .

**Comment by nhill308** [comment]
On step 6 when i run chmod +x ./DayZLauncher.UnixPatcher from terminal i get this .....(deck@steamdeck DayZLauncher-UnixPatcher-main)$ chmod +x ./DayZLauncher.UnixPatcher
chmod: cannot access './DayZLauncher.UnixPatcher': No such file or directory.
 after I downloaded and extracted the file there isnt anything named DayZLauncher.UnixPatcher inside
![364070638_196890666514370_5923858797746789257_n](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/assets/98241885/04110cc0-04a4-4f80-9c3a-306d67a366fd)

**Comment by nhill308** [comment]
![364070638_196890666514370_5923858797746789257_n](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/assets/98241885/0cd034dc-a2ba-45bf-9599-f35f74789f49)

**Comment by valters-tomsons** [comment]
https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/releases/tag/1.2.8-dev0

Download the release build, not source code.

**Comment by nhill308** [comment]
LOL no wonder I was so lost . That helps alot . Thank you for all the help!
