### ISSUE TITLE
seems to re-download the game on 1.23

### ISSUE THREAD

**Issue by chrisbward** [valters-tomsons/DayZLauncher-UnixPatcher#6]
Hi - just patched 1.23, and the game has started downloading again?

Has something changed here? Great job btw

**Comment by chrisbward** [comment]
ahhh maybe because I didn't follow the Updating steps, I will verify this once it's downloaded again

**Comment by valters-tomsons** [comment]
This mod cannot really affect how or when steam downloads a game, not related.
