### ISSUE TITLE
Mods fail to install, unable to be loaded - "waiting to be installed"

### ISSUE THREAD

**Issue by Samg381** [valters-tomsons/DayZLauncher-UnixPatcher#8]
Mods are able to be downloaded, but the downloads hang indefinitely. In the Mods tab, all mods show as 'Not installed' and cannot be activated. Ubuntu 24.04.

![Screenshot from 2024-04-14 16-18-52](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/assets/3127698/493c952a-116b-4991-acb7-720e2c29ce04)

![Screenshot from 2024-04-14 16-23-31](https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/assets/3127698/6bc5f443-b885-4ea1-be08-e5e52a53cd90)

**Comment by valters-tomsons** [comment]
Will fix :+1:

**Comment by valters-tomsons** [comment]
Should be fixed as of https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/commit/b912c9fd585449284c6175aa8556d7ea3b903675, will make a release soon. :+1:

**Comment by Samg381** [comment]
Thanks! And yes, please do- looking forward to the release!

**Comment by Samg381** [comment]
@valters-tomsons any hope for a release?

**Comment by valters-tomsons** [comment]
No promises, something else is broken and haven't had the interest to look at it again.

**Comment by valters-tomsons** [comment]
Will release today.

**Comment by valters-tomsons** [comment]
See https://github.com/valters-tomsons/DayZLauncher-UnixPatcher/releases/tag/1.4.0
